using Jay.SourceGen.Extensions;
using Jay.SourceGen.Text;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text;

namespace Jay.SourceGen.InterfaceGen;

internal class InterfaceCodeGen
{
    public SourceCode Generate(TypeSymbolInfo typeSymbolInfo)
    {
        using var code = new CodeBuilder();

        code.AutoGeneratedHeader()
            .Nullable(true)
            .Namespace(typeSymbolInfo.Type.GetNamespace())
            .NewLine()
            .Code($"partial {typeSymbolInfo.Type} : ");

        var interfaces= typeSymbolInfo.Interfaces;

        Debugger.Break();
        throw new NotImplementedException();
    }
}
